export const ADMIN_LOADING = 'ADMIN_LOADING';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const GET_MARKETS = 'GET_MARKETS';
export const GET_MARKET = 'GET_MARKET';
export const DELETE_MARKET = 'DELETE_MARKET';
export const ADD_MARKET = 'ADD_MARKET';
export const UPDATE_MARKET = 'UPDATE_MARKET';
export const MARKET_ERROR = 'MARKET_ERROR';
export const GET_CATEGORIES = 'GET_CATEGORIES';
